import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Auto-generated sidebars
  docsSchoolSidebar: [{type: 'autogenerated', dirName: 'school'}],
};

export default sidebars;