import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Auto-generated sidebars
  devprinciplesSidebar: [{type: 'autogenerated', dirName: 'devprinciples'}],
  langSidebar: [{type: 'autogenerated', dirName: 'lang'}],
  osSidebar: [{type: 'autogenerated', dirName: 'os'}],
  toolsSidebar: [{type: 'autogenerated', dirName: 'tools'}],
  webdevSidebar: [{type: 'autogenerated', dirName: 'webdev'}],
};

export default sidebars;
