name: Build and Deploy
on:
  push:
    branches:
      - main  # Setzt dies auf den Namen eures Produktionsbranches

jobs:
  build:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '19.3.0'  # Setzt die Node-Version entsprechend eurer Projektanforderungen

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./build"  # Pfad zum Build-Verzeichnis
          target: "/var/www/wiki"  # Zielverzeichnis auf eurem Server